package GUI_Forms;
import Functions.Log_in;
import SQL_Conn.DatabaseConnectionInnit;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Functions.Log_in;
import SQL_Conn.DatabaseConnectionInnit;
import javax.swing.JOptionPane;

public class User_AdminPassword extends javax.swing.JFrame {
Log_in log = new Log_in();
DatabaseConnectionInnit user = new DatabaseConnectionInnit();
    public User_AdminPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        haha2 = new javax.swing.JPanel();
        haha1 = new javax.swing.JPanel();
        hehe1 = new javax.swing.JLabel();
        hehe2 = new javax.swing.JLabel();
        hehe3 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        Old_pass = new javax.swing.JTextField();
        New_pass = new javax.swing.JTextField();
        hehe4 = new javax.swing.JLabel();
        hehe5 = new javax.swing.JRadioButton();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INVENTORY SYSTEM_ADMIN PASSWORD MANAGER");
        setResizable(false);

        haha2.setBackground(new java.awt.Color(102, 102, 102));

        haha1.setBackground(new java.awt.Color(2, 39, 60));

        hehe1.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        hehe1.setForeground(new java.awt.Color(255, 255, 255));
        hehe1.setText("EMAIL:");

        hehe2.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        hehe2.setForeground(new java.awt.Color(255, 255, 255));
        hehe2.setText("OLD PASSWORD:");

        hehe3.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        hehe3.setForeground(new java.awt.Color(255, 255, 255));
        hehe3.setText("NEW PASSSWORD:");

        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });

        hehe4.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        hehe4.setForeground(new java.awt.Color(255, 255, 255));
        hehe4.setText("Authority:");

        hehe5.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        hehe5.setForeground(new java.awt.Color(255, 255, 255));
        hehe5.setText("Admin");
        hehe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hehe5ActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFY:");

        javax.swing.GroupLayout haha1Layout = new javax.swing.GroupLayout(haha1);
        haha1.setLayout(haha1Layout);
        haha1Layout.setHorizontalGroup(
            haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(haha1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(haha1Layout.createSequentialGroup()
                        .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hehe1)
                            .addComponent(hehe4)
                            .addComponent(hehe3)
                            .addComponent(hehe2))
                        .addGap(18, 18, 18)
                        .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(New_pass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Old_pass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, haha1Layout.createSequentialGroup()
                                .addComponent(hehe5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(update))
                            .addComponent(User, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(haha1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        haha1Layout.setVerticalGroup(
            haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(haha1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hehe1)
                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Old_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hehe2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(haha1Layout.createSequentialGroup()
                        .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hehe3)
                            .addComponent(New_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(haha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hehe5)
                            .addComponent(hehe4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, haha1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(update)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout haha2Layout = new javax.swing.GroupLayout(haha2);
        haha2.setLayout(haha2Layout);
        haha2Layout.setHorizontalGroup(
            haha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(haha2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(haha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        haha2Layout.setVerticalGroup(
            haha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, haha2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(haha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(haha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(haha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void hehe5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hehe5ActionPerformed

    }//GEN-LAST:event_hehe5ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        log.setUser_Nme(User.getText());
        log.setOUser_pass(Old_pass.getText());
        log.setNUser_pass(New_pass.getText());
        String auth = "";
        int choice = JOptionPane.showConfirmDialog(this, "You are about to MODIFY this user.\n\n ARE YOU SURE?", "MODIFY",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
         if(choice == JOptionPane.YES_OPTION)
         {
        if (SQL_Conn.SQL_Conn.dbUpdChecker(log.getUser_Nme(), log.getOUser_pass())){
            if (hehe5.isSelected()){
                auth = "Admin";
            }else if (!hehe5.isSelected()){
                auth = "Viewer";
            }
            user.dbUpdateUserTable(log.getUser_Nme(), log.getNUser_pass(), auth);
            this.dispose();
            JOptionPane.showMessageDialog(null, "YAY! You have changed the account", "It worked?!?!?!", JOptionPane.PLAIN_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(this, "Email or Password is incorrect", "Input error", 0);
        }
         }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_AdminPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField New_pass;
    private javax.swing.JTextField Old_pass;
    private javax.swing.JTextField User;
    private javax.swing.JPanel haha1;
    private javax.swing.JPanel haha2;
    private javax.swing.JLabel hehe1;
    private javax.swing.JLabel hehe2;
    private javax.swing.JLabel hehe3;
    private javax.swing.JLabel hehe4;
    private javax.swing.JRadioButton hehe5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
