/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SENDS;
import SENDS.FirebaseConnection;
import GUI.UI.Login;

import java.io.IOException;
import java.io.FileInputStream;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        Scanner scn = new Scanner(System.in);
        int tester = 0;
        System.out.println(new App().getGreeting());
        try{
        FirebaseConnection.fbdbInit();
            System.out.println("success");
        }catch (IOException e){
            System.out.println("failed");
            System.out.println(e);
        }
        System.out.println(tester);
        
        Login login = new Login();
        login.setVisible(true);
    }
}
